spring:
  main: #kakaoApiBean
    allow-bean-definition-overriding: true

#aws
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER_NAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update #create
    show-sql: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true

mail: #관리자 이메일 정보 등록
  address:
    admin: ${ADMIN_MAIL}

#h2
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
#    jpa:
#      hibernate:
#        ddl-auto: create
#      show-sql: true
#      database: mysql
#      properties:
#        hibernate:
#          show_sql: true
#          format_sql: true

kakao:
  key: ${KAKAO_KEY}

